name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Retrieve version
        run: |
          version=`awk -F "=" '$1 == "version" {print $2}' gradle.properties`
          commit_count=`git rev-list HEAD --count`
          version="${version}.r${commit_count}"
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Build with gradle
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew --no-daemon -Pversion=$VERSION dist

      - name: Upload integrations and patches
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: BiliRoamingX-${{ env.VERSION }}
          path: 'build'
